### PR TITLE
Thermostat

### PR DESCRIPTION
**Pull request by torandreroland**
Change service from TemperatureSensor to Thermostat

### CODE REVIEW

**Comment by ebaauw** [comment]
That's a bug alright, but you changed the wrong file.  It should be `DeconzService/Thermostat.js`.

I no longer use my Eurotronic Spirit TRVs, so haven't yet tested this.

**Comment by torandreroland** [comment]
Thanks for spotting that I changed the wrong file and fixing the issue.

**Comment by ebaauw** [comment]
Can you please confirm that the Elko now works (with the change to `Thermostat.js`)?

**Comment by ebaauw** [comment]
In v0.0.13.

**Pull request closed without merging**
